### ISSUE TITLE
No chapter menu on pages

### ISSUE THREAD

**Issue by peiche** [hyunsupul/aesop-core#324]
I have a demo site running the Aesop Story Theme. When I have chapter components in a post, the chapter menu appears like it should:
http://rich-fox.w2.poopy.life/2017/04/11/chapter-post-test/

But when I do the same on a page (and it's the exact same source), there is no chapter menu:
http://rich-fox.w2.poopy.life/chapter-page-test/

**Comment by hyunsupul** [comment]
Hi Paul,
Aesop chapter components looks for and works on ".aesop-entry-content" or ".entry-content."  Since the page didn't have either class it didn't insert the chapter menu. I don't know why the original author didn't think it important to enable it for pages. But if you are writing your own theme you can insert one of those two classes to the pages and enable chapters. If you have a suggestion on how to make it work better for pages in general feel free to let me know.

Hyun
